### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by TheGoldenChicken** [DrJupiter/HumanCognition#1]
Running graphical.py raises an import error, as pygame 1.9.6 is unable to import WINDOWFOCUSLOST from pygame.constants

Removing the constant fixes it, it isn't really used

**Comment by DrJupiter** [comment]
This has been fixed in the latest commit and is presumably a backwards compatibility error between pygame version 1. and 2..

**Comment by DrJupiter** [comment]
Link to commit with change: https://github.com/DrJupiter/HumanCognition/commit/0888d4cebadfe6d97840d4e5d35671a58d8df871

**Comment by DrJupiter** [comment]
The help text has also been updated for week 1; specifying how to upgrade ones packages and thereby pygame version.
